# Generated by Django 2.2.6 on 2019-10-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, null=True, verbose_name='Nome: ')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, null=True, verbose_name='Número')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Titulo')),
                ('data', models.DateField(null=True, verbose_name='Data:')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome: ')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, null=True, verbose_name='Número')),
                ('data_criacao', models.DateField(null=True, verbose_name='Data da Criação:')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_processo.Departamento')),
                ('interessado', models.ManyToManyField(related_name='Iteressado', to='app_processo.Pessoa')),
                ('investigado', models.ManyToManyField(related_name='Investigado', to='app_processo.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Pessoa')),
                ('matricula', models.CharField(max_length=20, null=True, verbose_name='Matricula: ')),
            ],
            bases=('app_processo.pessoa',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('justificativa', models.CharField(max_length=120, null=True, verbose_name='Justificativa: ')),
                ('prazo_anterior', models.DateField(null=True, verbose_name='Prazo Anterior: ')),
                ('prazo_novo', models.DateField(null=True, verbose_name='Prazo Novo: ')),
            ],
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome: ')),
            ],
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='app_processo.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='app_processo.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_processo.Funcionario'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('data_envio', models.DateField(null=True, verbose_name='Data de envio:')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_processo.Departamento')),
            ],
            bases=('app_processo.documento',),
        ),
    ]
